language: elixir
sudo: false
elixir:
  - 1.6
  - 1.7
otp_release:
  - 20.2
  - 21.1
env:
  - MIX_ENV=test
script:
  - mix test
services:
  - redis-server
cache:
  directories:
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.7
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.7
